spring.application.name=user
spring.sql.init.mode=always
server.port=8000
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
management.endpoints.web.exposure.include=prometheus
management.metrics.tags.application=monitorable-application
management.metrics.distribution.percentiles-histogram.http.server.requests=true
