replicaCount: 2

autoscaling:
  enabled: false

image:
  repository: kseniasharapova/user-app:1.0.0
  pullPolicy: IfNotPresent
  tag: "user-app"

nameOverride: "user-app"
fullnameOverride: "user-app"

podLabels: {
  "app": "user-app"
}
service:
  type: ClusterIP
  port: 8000

httpRoute:
  enabled: false

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix

# Additional volumes on the output Deployment definition.
volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false
auth:
  enablePostgresUser: true
  username: "dXNlcg=="
  password: "MTIzNDU="
  postgresPassword: "dXNlcg=="

database:
  url: "jdbc:postgresql://postgres-service:5432/mydb"

