apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mychart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mychart.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for postgres to be ready..."
              until nc -z -v -w3 {{ .Release.Name }}-postgresql 5432; do
                echo "Postgres is unavailable - sleeping"
                sleep 2
              done
              echo "Postgres is up and running!"
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mychart.fullname" . }}
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "mychart.fullname" . }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mychart.fullname" . }}
                  key: password