apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . }}
type: Opaque
data:
  {{- if .Values.auth.enablePostgresUser }}
  postgres-password: {{ required "The new postgres password is required!" .Values.auth.postgresPassword | b64enc | quote }}
  {{- end }}
  {{- if and (not (empty .Values.auth.username)) (ne .Values.auth.username "postgres") }}
  username: {{ required "The new user password is required!" .Values.auth.username | b64enc | quote }}
  password: {{ required "The new user password is required!" .Values.auth.password | b64enc | quote }}
  {{- end }}