apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . }}
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}