apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . }}
type: Opaque
data:
  postgres-password: {{ required "postgresPassword is required" .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  username: {{ required "auth.username is required" .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ required "auth.password is required" .Values.postgresql.auth.password | b64enc | quote }}
